#ifndef BUTEOGCONTACTPLUGIN_GLOBAL_H
#define BUTEOGCONTACTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUTEOGCONTACTPLUGIN_LIBRARY)
#  define BUTEOGCONTACTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUTEOGCONTACTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTEOGCONTACTPLUGIN_GLOBAL_H
